import { Product } from "@/lib/types";

// === UNIQUE IMAGE SETS PER PRODUCT ===
const img = {
  // Nails (6 unique sets)
  n01: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800",
  n01b: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=800",
  n01c: "https://images.unsplash.com/photo-1607779097040-26e80aa78e66?w=800",
  n02: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=800",
  n02b: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800",
  n02c: "https://images.unsplash.com/photo-1601050690117-94f5f1e1a1c8?w=800",
  n03: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
  n03b: "https://images.unsplash.com/photo-1487412912498-0447578fcca8?w=800",
  n04: "https://images.unsplash.com/photo-1485965373059-f07657e9f841?w=800",
  n04b: "https://images.unsplash.com/photo-1491895200222-0fc4a4c35e18?w=800",
  n05: "https://images.unsplash.com/photo-1580111644429-7934c42e7c46?w=800",
  n05b: "https://images.unsplash.com/photo-1601050690371-1e2bb14aead8?w=800",
  n06: "https://images.unsplash.com/photo-1604654895102-1a14d1ba1b4d?w=800",
  n06b: "https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=800",

  // Beauty (6 unique sets)
  b01: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800",
  b01b: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800",
  b02: "https://images.unsplash.com/photo-1570194065650-d99fb4e8a107?w=800",
  b02b: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=800",
  b03: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800",
  b03b: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800",
  b04: "https://images.unsplash.com/photo-1505944270255-72b8c68c6a70?w=800",
  b04b: "https://images.unsplash.com/photo-1599305090598-fe179d501227?w=800",
  b05: "https://images.unsplash.com/photo-1617897903246-719242758050?w=800",
  b05b: "https://images.unsplash.com/photo-1556229162-5c63ed9c4efb?w=800",
  b06: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800",
  b06b: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800",

  // Charms (6 unique sets)
  c01: "https://images.unsplash.com/photo-1611080626919-7cf3a48dd71b?w=800",
  c01b: "https://images.unsplash.com/photo-1604004555489-723a93d6ce74?w=800",
  c02: "https://images.unsplash.com/photo-1621605815971-fbc98d66556e?w=800",
  c02b: "https://images.unsplash.com/photo-1576053139778-7e32f2ae3cfd?w=800",
  c03: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800",
  c03b: "https://images.unsplash.com/photo-1594535182308-8ffefbb661e1?w=800",
  c04: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800",
  c04b: "https://images.unsplash.com/photo-1599643478518-a784a7b8c863?w=800",
  c05: "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f9?w=800",
  c05b: "https://images.unsplash.com/photo-1543322748-33df6d3db806?w=800",
  c06: "https://images.unsplash.com/photo-1624623278313-a930126a11c3?w=800",
  c06b: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800",

  // Accessories (6 unique sets)
  a01: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800",
  a01b: "https://images.unsplash.com/photo-1583394833573-d49f3a66d816?w=800",
  a02: "https://images.unsplash.com/photo-1629224316810-9d8805b95e76?w=800",
  a02b: "https://images.unsplash.com/photo-1611923134239-b9be5816e23a?w=800",
  a03: "https://images.unsplash.com/photo-1600721392183-26a3f6b1f39b?w=800",
  a03b: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
  a04: "https://images.unsplash.com/photo-1633810542706-8e8abe3b1881?w=800",
  a04b: "https://images.unsplash.com/photo-1543163521-1bf539c55b08?w=800",
  a05: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800",
  a05b: "https://images.unsplash.com/photo-1608236415055-2132264b7914?w=800",
  a06: "https://images.unsplash.com/photo-1515562141567-5491576cd09f?w=800",
  a06b: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=800",
};

export const products: Product[] = [
  // ════════════ PRESS-ON NAILS (6) ════════════
  {
    id: "nail-01",
    name: "French Bliss",
    nameZh: "法式温柔",
    category: "press-on-nails",
    price: 24.99, originalPrice: 34.99,
    images: [img.n01, img.n01b, img.n01c],
    description: "Classic French tips reimagined with a soft almond silhouette. Each set is hand-painted with a micro-shimmer base that catches the light. 24 nails, 12 sizes, reusable up to 14 days.",
    descriptionZh: "经典法式尖，杏仁形轮廓。每套手工涂绘微闪底胶。24片12尺寸，可重复使用14天。",
    features: ["Hand-painted French tips", "Micro-shimmer base", "Almond silhouette", "Reusable up to 14 days", "24 nails + application kit"],
    material: "Premium gel + ABS", colors: ["Natural Pink", "Milky White", "Nude Beige"], sizes: ["XS", "S", "M", "L"],
    inStock: true, isNew: false, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["French Tip", "Classic", "Bridal", "Office"],
    tiktokVideo: "https://tiktok.com/@ausbeautyshop", instagramPost: "https://instagram.com/ausbeautyshop",
  },
  {
    id: "nail-02",
    name: "3D Botanica",
    nameZh: "3D立体花卉",
    category: "press-on-nails",
    price: 32.99,
    images: [img.n02, img.n02b, img.n02c],
    description: "Intricate 3D floral relief with hand-placed dried petals, pearls, and gold foil. Each nail is a wearable sculpture — made for moments worth remembering.",
    descriptionZh: "3D花卉浮雕，手工干花+珍珠+金箔。每一片都是可穿戴的艺术品。",
    features: ["3D relief flowers", "Dried petals & gold foil", "Hand-applied pearls", "24 nails, 12 sizes", "Gallery-grade packaging"],
    material: "Gel + resin + natural dried flowers", colors: ["Blush", "Ivory", "Sakura"], sizes: ["XS", "S", "M", "L"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["3D", "Floral", "Wedding", "Art"],
  },
  {
    id: "nail-03",
    name: "Matte Macaron",
    nameZh: "哑光马卡龙",
    category: "press-on-nails",
    price: 19.99, originalPrice: 27.99,
    images: [img.n03, img.n03b, img.n02c],
    description: "Six dreamy pastels with a velvety matte topcoat. Light as air, ideal for everyday. Korean-street-style inspired.",
    descriptionZh: "六色马卡龙哑光穿戴甲，柔雾质感，轻若无物，韩系街头风格。",
    features: ["Velvet matte finish", "6 interchangeable colors", "Ultra-light wear", "24 nails kit", "Daily + editorial looks"],
    material: "Matte gel + ABS", colors: ["Lavender", "Mint", "Peach", "Baby Blue", "Pink", "Lemon"], sizes: ["XS", "S", "M", "L"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Matte", "Pastel", "Korean", "Daily"],
  },
  {
    id: "nail-04",
    name: "Glass Chrome",
    nameZh: "玻璃镜面",
    category: "press-on-nails",
    price: 27.99,
    images: [img.n04, img.n04b, img.n01c],
    description: "High-shine chrome with a glass-like transparency. The mirror finish shifts under different light — futuristic yet wearable.",
    descriptionZh: "高光镜面铬效果，玻璃般透明。镜面在不同光线下变幻，未来感十足。",
    features: ["Chrome mirror finish", "Glass transparency effect", "Light-shifting technology", "24 nails kit", "TikTok viral look"],
    material: "Chrome gel + ABS", colors: ["Silver", "Rose Gold", "Holographic"], sizes: ["XS", "S", "M", "L"],
    inStock: true, isNew: true, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Chrome", "Mirror", "Futuristic", "Statement"],
    tiktokVideo: "https://tiktok.com/@ausbeautyshop",
  },
  {
    id: "nail-05",
    name: "Aurora Marble",
    nameZh: "极光大理石",
    category: "press-on-nails",
    price: 29.99,
    images: [img.n05, img.n05b, img.n02c],
    description: "Swirling marble veins over a translucent aurora base. Each set is unique — no two nails are ever alike.",
    descriptionZh: "大理石纹理叠加极光底色，每套独一无二。",
    features: ["Real marble-effect veins", "Aurora translucent base", "One-of-a-kind pattern", "24 nails kit", "Luxe gift box"],
    material: "Gel + marble pigment", colors: ["Aurora White", "Cosmic Blue", "Rose Quartz"], sizes: ["XS", "S", "M", "L"],
    inStock: true, isNew: false, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Marble", "Aurora", "Luxe", "Gift"],
  },
  {
    id: "nail-06",
    name: "Minimalist Line Art",
    nameZh: "极简线条",
    category: "press-on-nails",
    price: 21.99,
    images: [img.n06, img.n06b, img.n03b],
    description: "Clean, architectural line drawings on a nude base. Inspired by contemporary gallery art — for the modern minimalist.",
    descriptionZh: "裸色底+建筑感线条，灵感来自当代画廊艺术，极简主义者的首选。",
    features: ["Hand-drawn line art", "Gallery-inspired design", "Nude micro-shimmer base", "24 nails kit", "Everyday elegance"],
    material: "Gel + ABS", colors: ["Nude + Black", "Nude + Gold", "Blush + White"], sizes: ["XS", "S", "M", "L"],
    inStock: true, isNew: true, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Minimalist", "Line Art", "Gallery", "Clean"],
  },

  // ════════════ BEAUTY TOYS (6) ════════════
  {
    id: "beauty-01",
    name: "SonicGlow™ Facial Brush",
    nameZh: "声波焕肤洁面仪",
    category: "beauty-toys",
    price: 39.99, originalPrice: 59.99,
    images: [img.b01, img.b01b, img.b02b],
    description: "5-mode sonic cleansing with built-in LED therapy (red, blue, green). IPX7 waterproof, USB-C rechargeable, 30-day battery. Removes 99% of makeup residue.",
    descriptionZh: "5模式声波+LED光疗（红/蓝/绿）。IPX7防水，USB-C充电，续航30天。99%卸妆清除率。",
    features: ["5 sonic modes + LED therapy", "IPX7 fully waterproof", "USB-C, 30-day battery", "3 interchangeable heads", "Travel case included"],
    material: "Medical-grade silicone + ABS", colors: ["Cloud White", "Sage Green", "Quartz Pink"], sizes: ["Standard"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Cleansing", "LED", "Skincare", "Waterproof"],
    tiktokVideo: "https://tiktok.com/@ausbeautyshop",
  },
  {
    id: "beauty-02",
    name: "Cryo Glow Ice Roller",
    nameZh: "冰晶焕肤滚轮",
    category: "beauty-toys",
    price: 24.99,
    images: [img.b02, img.b02b, img.b01b],
    description: "Freeze-activated roller with a genuine quartz head. Instantly depuffs, tightens pores, and boosts circulation. Keep in the freezer for the full cryo experience.",
    descriptionZh: "冷冻激活，真石英滚轮头。即刻消肿、紧致毛孔、促进循环。放入冰箱体验冷冻焕肤。",
    features: ["Genuine quartz roller head", "Freezer-safe (–20°C)", "Anti-puff, pore-tightening", "Ergonomic grip", "All skin types"],
    material: "Rose quartz + stainless steel + silicone", colors: ["Rose Quartz", "Clear Crystal", "Jade"], sizes: ["Standard"],
    inStock: true, isNew: false, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Face Roller", "Cryo", "Quartz", "Depuff"],
  },
  {
    id: "beauty-03",
    name: "AirMist™ Portable Spray",
    nameZh: "迷你雾化喷枪",
    category: "beauty-toys",
    price: 49.99, originalPrice: 69.99,
    images: [img.b03, img.b03b, img.b04b],
    description: "Pocket-sized airbrush for flawless foundation. 0.3 mm ultra-fine nozzle, 3 spray patterns, USB-C rechargeable. Fits in a clutch — red-carpet finish anywhere.",
    descriptionZh: "口袋大小喷枪化妆仪，0.3mm超细雾化，3档喷雾，USB-C充电。随身携带红毯妆感。",
    features: ["0.3 mm micro-mist nozzle", "3 adjustable patterns", "Fits in handbag", "USB-C fast charge", "Works with any liquid foundation"],
    material: "ABS + stainless steel", colors: ["Rose Gold", "Matte Black", "Pearl"], sizes: ["Mini"],
    inStock: true, isNew: true, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Makeup", "Airbrush", "Portable", "Pro"],
  },
  {
    id: "beauty-04",
    name: "Gua Sha Sculpting Set",
    nameZh: "刮痧塑颜套装",
    category: "beauty-toys",
    price: 28.99,
    images: [img.b04, img.b04b, img.b03b],
    description: "Authentic bian-stone gua sha tool + rose quartz roller. Traditional technique meets modern ergonomics. Includes guided routine card with 8 sculpting movements.",
    descriptionZh: "正宗砭石刮痧板+粉晶滚轮。传统技法融入现代工学设计。含8步塑颜手法指导卡。",
    features: ["Authentic bian-stone + rose quartz", "8-movement guided routine", "Lymphatic drainage", "Sculpts jawline & cheekbones", "Velvet pouch included"],
    material: "Bian-stone + rose quartz", colors: ["Stone Grey", "Rose"], sizes: ["Standard"],
    inStock: true, isNew: false, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Gua Sha", "Sculpting", "Traditional", "Wellness"],
  },
  {
    id: "beauty-05",
    name: "LumiMask™ LED Therapy",
    nameZh: "LED光子面罩",
    category: "beauty-toys",
    price: 89.99, originalPrice: 129.99,
    images: [img.b05, img.b05b, img.b06b],
    description: "Full-face LED mask with 150 medical-grade LEDs. 4 wavelengths target acne, wrinkles, hyperpigmentation, and inflammation. 10-min daily ritual.",
    descriptionZh: "全脸LED面罩，150颗医用级灯珠，4种波长针对痘痘、皱纹、色斑、炎症。每天10分钟。",
    features: ["150 medical-grade LEDs", "4 therapeutic wavelengths", "10-min auto timer", "Lightweight (280 g)", "USB-powered"],
    material: "Medical silicone + ABS", colors: ["White"], sizes: ["One Size"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["LED Mask", "Anti-aging", "Acne", "Device"],
  },
  {
    id: "beauty-06",
    name: "NanoMist Hydration Pen",
    nameZh: "纳米补水喷雾笔",
    category: "beauty-toys",
    price: 19.99,
    images: [img.b06, img.b06b, img.b05b],
    description: "Ultrasonic nano-mist pen that transforms toner or water into ultra-fine hydrating particles. 30-second full-face hydration — throw it in your bag for mid-day refresh.",
    descriptionZh: "超声波纳米喷雾笔，将化妆水雾化成超细粒子。30秒全脸补水，放包里随时补水。",
    features: ["Ultrasonic nano-mist", "30-second full-face", "Works with any toner", "USB rechargeable", "Pocket-sized (14 cm)"],
    material: "ABS + ultrasonic module", colors: ["Matte White", "Blush"], sizes: ["Mini (14 cm)"],
    inStock: true, isNew: true, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Mist", "Hydration", "Portable", "Travel"],
  },

  // ════════════ BAG CHARMS (6) ════════════
  {
    id: "charm-01",
    name: "Teddy Bear Charm",
    nameZh: "泰迪熊挂件",
    category: "bag-charms",
    price: 15.99,
    images: [img.c01, img.c01b, img.c02b],
    description: "Miniature plush teddy with hand-embroidered face and a polished gold clasp. 8 cm of pure joy — clips onto any bag, keychain, or rearview mirror.",
    descriptionZh: "迷你毛绒泰迪，手工刺绣表情+抛光金扣。8cm纯真快乐，可挂在任何包袋或钥匙上。",
    features: ["Hand-embroidered face", "Gold-tone alloy clasp", "Super-soft plush (8 cm)", "Universal clip", "Collectible series"],
    material: "Plush + alloy", colors: ["Caramel", "Cream", "Blush"], sizes: ["8 cm"],
    inStock: true, isNew: false, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Teddy", "Cute", "Bag Charm", "Gift"],
  },
  {
    id: "charm-02",
    name: "Pearl Cascade Chain",
    nameZh: "珍珠瀑布链",
    category: "bag-charms",
    price: 22.99, originalPrice: 29.99,
    images: [img.c02, img.c02b, img.c01b],
    description: "Graduated faux-pearl chain with vintage gold links. Drapes beautifully across any bag silhouette. Doubles as a short necklace.",
    descriptionZh: "渐变仿珍珠链+复古金链节，优雅垂坠在任何包型上。也可作为短项链佩戴。",
    features: ["Graduated pearl drops", "Vintage gold links", "Lobster clasp", "30 cm length", "Bag charm + necklace"],
    material: "Faux pearls + alloy", colors: ["Ivory Pearl", "Blush Pearl", "Noir"], sizes: ["30 cm"],
    inStock: true, isNew: true, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Pearl", "Elegant", "Dual-use", "Luxe"],
  },
  {
    id: "charm-03",
    name: "Sakura Pom Pom",
    nameZh: "樱花毛球",
    category: "bag-charms",
    price: 12.99,
    images: [img.c03, img.c03b, img.c04b],
    description: "Cloud-soft faux-fur pom pom with a cherry blossom center. Floats like cotton candy on your favorite bag. Four candy colors.",
    descriptionZh: "云朵般柔软人造毛毛球+樱花花心。像棉花糖一样装点你的包，4种糖果色。",
    features: ["Ultra-soft faux fur", "Cherry blossom motif", "Quick-clip attachment", "10 cm diameter", "4 candy colors"],
    material: "Faux fur + alloy", colors: ["Sakura", "Milk White", "Lavender", "Matcha"], sizes: ["10 cm"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Pom Pom", "Fluffy", "Kawaii", "Candy"],
    tiktokVideo: "https://tiktok.com/@ausbeautyshop",
  },
  {
    id: "charm-04",
    name: "Mini Letter Bead Strap",
    nameZh: "字母串珠挂绳",
    category: "bag-charms",
    price: 14.99,
    images: [img.c04, img.c04b, img.c03b],
    description: "Customizable letter-bead strap — spell your name, a mantra, or a vibe. Colorful acrylic beads on a strong nylon cord. TikTok's favorite DIY charm.",
    descriptionZh: "可自定字母串珠挂绳—拼你的名字或座右铭。彩色亚克力珠+强韧尼龙绳。TikTok热门DIY。",
    features: ["Customizable letters", "20+ bead colors", "Strong nylon cord", "Adjustable length", "Personalizable gift"],
    material: "Acrylic beads + nylon + alloy", colors: ["Rainbow", "Pastel", "Neon"], sizes: ["Adjustable 20–30 cm"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Beaded", "Custom", "DIY", "TikTok"],
  },
  {
    id: "charm-05",
    name: "Resin Flower Pendant",
    nameZh: "树脂干花挂坠",
    category: "bag-charms",
    price: 18.99,
    images: [img.c05, img.c05b, img.c06b],
    description: "Real dried flower encased in crystal-clear resin, set in a gold-toned bezel. Each pendant captures a different bloom — a tiny forever garden.",
    descriptionZh: "真干花封存于晶莹树脂中，金色边框。每一枚都是不同的花朵—一座小小的永恒花园。",
    features: ["Real dried flower inside", "Crystal-clear resin", "Gold-tone bezel setting", "4 cm diameter", "Each piece unique"],
    material: "Resin + dried flower + alloy", colors: ["Daisy", "Lavender", "Rose", "Forget-me-not"], sizes: ["4 cm"],
    inStock: true, isNew: false, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Resin", "Dried Flower", "Artisan", "Unique"],
  },
  {
    id: "charm-06",
    name: "Cosmic Star Charm",
    nameZh: "宇宙星星挂件",
    category: "bag-charms",
    price: 16.99,
    images: [img.c06, img.c06b, img.c05b],
    description: "Holographic star charm with a iridescent shimmer. Catches light from every angle — turns any bag into a galaxy.",
    descriptionZh: "全息星星挂件，彩虹偏光。每个角度都折射不同的光—让任何包变成银河。",
    features: ["Holographic iridescent finish", "3D star shape (6 cm)", "Light-catching facets", "Gold clasp", "Space-themed packaging"],
    material: "Holographic acrylic + alloy", colors: ["Iridescent", "Aurora"], sizes: ["6 cm"],
    inStock: true, isNew: true, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Holographic", "Star", "Cosmic", "Y2K"],
  },

  // ════════════ ACCESSORIES (6) ════════════
  {
    id: "acc-01",
    name: "Korean Hair Claw Trio",
    nameZh: "韩式发抓三件套",
    category: "accessories",
    price: 18.99,
    images: [img.a01, img.a01b, img.a02b],
    description: "Three statement hair claws in tortoise, milk, and honey. Strong cellulose acetate with a polished finish. Grips all hair types without snagging.",
    descriptionZh: "三枚造型发抓：玳瑁、牛奶、蜂蜜琥珀。醋酸纤维抛光，不卡发，强抓力。",
    features: ["Set of 3 statement claws", "Cellulose acetate", "No-snag spring", "Grip for thick & fine hair", "Gift-ready box"],
    material: "Cellulose acetate + spring", colors: ["Tortoise", "Milk", "Honey"], sizes: ["Medium (10 cm)"],
    inStock: true, isNew: false, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Hair Claw", "Korean", "Acetate", "Set"],
  },
  {
    id: "acc-02",
    name: "Beaded Phone Strap",
    nameZh: "串珠手机绳",
    category: "accessories",
    price: 11.99,
    images: [img.a02, img.a02b, img.a01b],
    description: "Hand-strung beaded strap with a secure phone-case anchor. Works for phones, cameras, keys, and small pouches. The accessory that TikTok can't stop posting.",
    descriptionZh: "手工串珠手机绳+安全锚片。手机/相机/钥匙/小包通用。TikTok刷屏款。",
    features: ["Hand-strung beads", "Secure case anchor", "Multi-device compatible", "Adjustable 20–30 cm", "Viral TikTok accessory"],
    material: "Acrylic beads + nylon + alloy", colors: ["Rainbow", "Pastel", "Neon", "Pearl"], sizes: ["Adjustable"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Phone Strap", "Beaded", "TikTok", "Multi-use"],
    tiktokVideo: "https://tiktok.com/@ausbeautyshop",
  },
  {
    id: "acc-03",
    name: "Silk Scrunchie Bundle",
    nameZh: "真丝发圈套装",
    category: "accessories",
    price: 25.99, originalPrice: 34.99,
    images: [img.a03, img.a03b, img.a04b],
    description: "Five 22-momme mulberry silk scrunchies in curated neutrals. Zero hair creasing, zero tugging. Sleep in them, style in them, gift them.",
    descriptionZh: "5条22姆米桑蚕丝发圈，精选中性色。零折痕，零拉扯。睡觉戴，出门戴，送礼佳品。",
    features: ["100% mulberry silk (22 momme)", "Zero crease, zero tug", "Set of 5 curated neutrals", "Washable & durable", "Gift box included"],
    material: "Mulberry silk", colors: ["Champagne", "Taupe", "Noir", "Blush", "Ivory"], sizes: ["Standard"],
    inStock: true, isNew: true, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Silk", "Scrunchie", "Luxe", "Haircare"],
  },
  {
    id: "acc-04",
    name: "Mini Hoop Earring Set",
    nameZh: "迷你耳圈套装",
    category: "accessories",
    price: 22.99,
    images: [img.a04, img.a04b, img.a03b],
    description: "Six pairs of mini hoops in 14K gold-plated brass — from sleek plain to textured twist. Hypoallergenic posts. Your everyday ear stack, sorted.",
    descriptionZh: "6对迷你耳圈，14K镀金黄铜。从光面到麻花纹理。防过敏耳针。日常叠戴一站式解决。",
    features: ["6 pairs (plain + textured)", "14K gold-plated brass", "Hypoallergenic posts", "Tarnish-resistant", "Travel pouch"],
    material: "Gold-plated brass", colors: ["14K Gold"], sizes: ["12–18 mm"],
    inStock: true, isNew: false, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Earrings", "Gold", "Minimalist", "Stack"],
  },
  {
    id: "acc-05",
    name: "Acrylic Sunglasses Chain",
    nameZh: "亚克力眼镜链",
    category: "accessories",
    price: 15.99,
    images: [img.a05, img.a05b, img.a06b],
    description: "Colorful chunky acrylic chain that keeps your sunnies safe and stylish. Clip it on, wear it as a necklace, never lose your shades again.",
    descriptionZh: "彩色粗亚克力链条，既当眼镜链也可当项链。再也不会丢墨镜了。",
    features: ["Chunky acrylic links", "Doubles as a necklace", "Universal silicone grips", "60 cm length", "5 color stories"],
    material: "Acrylic + silicone + alloy", colors: ["Tortoise", "Amber", "Candy", "Monochrome", "Ocean"], sizes: ["60 cm"],
    inStock: true, isNew: true, isHot: false,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Sunglasses", "Chain", "Acrylic", "Dual-use"],
  },
  {
    id: "acc-06",
    name: "Pearl Hair Pin Set",
    nameZh: "珍珠发夹套装",
    category: "accessories",
    price: 19.99,
    images: [img.a06, img.a06b, img.a05b],
    description: "Eight delicate hair pins tipped with freshwater pearls and gold-tone leaves. Scatter them through an updo or wear one as a subtle accent.",
    descriptionZh: "8枚精致发夹，淡水珍珠+金叶点缀。散落在盘发间或单戴点睛。",
    features: ["Freshwater pearls", "Gold-tone leaf accents", "Set of 8 pins", "Non-slip grip", "Gift packaging"],
    material: "Freshwater pearl + gold-plated brass", colors: ["Ivory Pearl", "Blush Pearl"], sizes: ["6 cm each"],
    inStock: true, isNew: false, isHot: true,
    shippingFrom: "China → Australia", estimatedDelivery: "7–12 business days",
    tags: ["Pearl", "Hair Pin", "Bridal", "Delicate"],
  },
];

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
export function getHotProducts(): Product[] {
  return products.filter((p) => p.isHot);
}
export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew);
}
